runtime: nodejs14
service: boilerplate
vpc_access_connector:
  name: projects/rely-296614/locations/northamerica-northeast1/connectors/rely
handlers:
- url: /.*
  script: auto
  secure: always
  http_headers:
    Strict-Transport-Security: 'max-age=63072000; includeSubDomains; preload'
  redirect_http_response_code: 301
