steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd /
    rm /workspace/src/microservices
    git clone -b main https://source.developers.google.com/p/relyrc/r/github_plogg-rely_microservices
    mv github_plogg-rely_microservices /workspace/src/microservices
    cd /workspace
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --project=devops-327318 --secret=boilerplate_env_production > env/production.env
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --project=devops-327318 --secret=boilerplate_elastic_production > .env
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--verbosity=debug"]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    versions=$(gcloud app versions list \
      --service boilerplate \
      --sort-by '~VERSION.ID' \
      --format 'value(VERSION.ID)' | sed 1,5d)
    for version in $versions; do
    gcloud app versions delete "$version" \
      --service boilerplate \
      --quiet
    done
timeout: "600s"
options:
  machineType: 'N1_HIGHCPU_8'
